FROM php:7.0-alpine

ENV APP_DIR /usr/src/app

WORKDIR $APP_DIR

ENV LARAVEL_VERSION 5.4

COPY . plugin
RUN mv plugin/ci ..

RUN chmod +x ../ci/scripts/*.sh
RUN ../ci/scripts/setup.sh

USER www-data

RUN ../ci/scripts/laravel.sh
WORKDIR $APP_DIR/integration
RUN $APP_DIR/../ci/scripts/integration.sh

CMD ["/bin/bash", "../../ci/scripts/integration-test.sh"]