version: "2"
plugins:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
      backward_compatibility_checks: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
  phpmd:
    enabled: true
  shellcheck:
    enabled: true
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - "tests/**"

exclude_patterns:
  - ".sami.*"
  - ".idea/**"
  - "ci/common/**"
  - "vendor/**"
  - "tests/**"
