pipeline:
  install:
    image: robbrazier/php:5.6
    commands:
      - composer install --no-suggest --no-progress
  php56:
    image: robbrazier/php:5.6
    group: test
    commands:
      - ./ci/unit.sh
  php70:
    image: robbrazier/php:7.0
    group: test
    commands:
      - ./ci/unit.sh
  php71:
    image: robbrazier/php:7.1
    group: test
    commands:
      - ./ci/unit.sh
  php72:
    image: robbrazier/php:7.2
    group: test
    commands:
      - ./ci/unit.sh

  laravel51:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - ./ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.1'
  laravel52:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - ./ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.2'
  laravel53:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - ./ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.3'
  laravel54:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - ./ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.4'
  laravel55:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - ./ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.5'
  
#   integrationTest:
#     image: robbrazier/php:${PHP_VERSION}
#     commands:
#       - ./ci/integration.sh
#     when:
#       matrix:
#         PHP_VERSION: '7.1'
      
# matrix:
#   PHP_VERSION:
#     - 5.6
#     - 7.0
#     - 7.1
#     - 7.2
#   LARAVEL_VERSION:
#     - 5.1
#     - 5.2
#     - 5.3
#     - 5.4
#     - 5.5