pipeline:
  unitTest:
    image: robbrazier/php:${PHP_VERSION}
    commands:
      - ./ci/unit.sh

  integrationTest:
    image: robbrazier/php:${PHP_VERSION}
    commands:
      - ./ci/integration.sh
      
matrix:
  PHP_VERSION:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
  LARAVEL_VERSION:
    - 5.1
    - 5.2
    - 5.3
    - 5.4
    - 5.5