pipeline:
  # Install dependencies
  install:
    image: robbrazier/php:5.6
    commands:
      - composer install --no-suggest --no-progress
  
  # Run unit tests
  php56:
    image: robbrazier/php:5.6
    group: test
    commands:
      - .ci/unit.sh
  php70:
    image: robbrazier/php:7.0
    group: test
    commands:
      - .ci/unit.sh
  php71:
    image: robbrazier/php:7.1
    group: test
    commands:
      - .ci/unit.sh
  php72:
    image: robbrazier/php:7.2
    group: test
    commands:
      - .ci/unit.sh

  # Run plugin integration tests
  laravel51:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - .ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.1'
  laravel52:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - .ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.2'
  laravel53:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - .ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.3'
  laravel54:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - .ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.4'
  laravel55:
    image: robbrazier/php:7.1
    group: integration
    commands: 
      - .ci/integration.sh
    environment:
      LARAVEL_VERSION: '5.5'

  # Run quality assurance (CodeClimate)
  qa:
    image: robbrazier/php:7.1
    commands:
      - .ci/qa.sh
    secrets: [ cc_test_reporter_id ]
  
  docs:
    image: robbrazier/php:7.1
    commands:
      - .ci/daux.sh
      - .ci/sami.sh
    when:
      branch: master
  deploy:
    image: node:6.11-alpine
    commands:
      - .ci/netlify.sh
    when:
      branch: master