cache:
  paths:
  - vendor/

image: robbrazier/php:5.6

before_script:
  - composer install --no-suggest --no-progress

stages:
  - unit
  - integration

jobs:
  # Run unit tests
  php56:
    image: robbrazier/php:5.6
    stage: unit
    script:
      - .ci/unit.sh
  php70:
    image: robbrazier/php:7.0
    stage: unit
    script:
      - .ci/unit.sh
  php71:
    image: robbrazier/php:7.1
    stage: unit
    script:
      - .ci/unit.sh
  php72:
    image: robbrazier/php:7.2
    stage: unit
    script:
      - .ci/unit.sh

  # Run plugin integration tests
  laravel51:
    image: robbrazier/php:7.1
    stage: integration
    script: 
      - .ci/integration.sh
    variables:
      LARAVEL_VERSION: '5.1'
  laravel52:
    image: robbrazier/php:7.1
    stage: integration
    script: 
      - .ci/integration.sh
    variables:
      LARAVEL_VERSION: '5.2'
  laravel53:
    image: robbrazier/php:7.1
    stage: integration
    script: 
      - .ci/integration.sh
    variables:
      LARAVEL_VERSION: '5.3'
  laravel54:
    image: robbrazier/php:7.1
    stage: integration
    script: 
      - .ci/integration.sh
    variables:
      LARAVEL_VERSION: '5.4'
  laravel55:
    image: robbrazier/php:7.1
    stage: integration
    script: 
      - .ci/integration.sh
    variables:
      LARAVEL_VERSION: '5.5'

  # Run quality assurance (CodeClimate)
#  qa:
#    image: robbrazier/php:7.1
#    commands:
#      - .ci/qa.sh
#    secrets: [ cc_test_reporter_id ]
  
#  docs:
#    image: robbrazier/php:7.1
#    commands:
#      - .ci/daux.sh
#      - .ci/sami.sh
#    when:
#      branch: master
#      event: deployment
#  deploy:
#    image: node:6.11-alpine
#    commands:
#      - .ci/netlify.sh
#    secrets: [ netlify_token ]
#    when:
#      branch: master
#      event: deployment
