language: php

php: 
  - 5.4
  - 5.5
  - 5.6
#  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

allow_failures:
  - php: 5.6
#  - php: hhvm

after_script:
  - php vendor/bin/coveralls
