version: '2'
services:
  php55:
    build:
      context: .
      args:
        PHP_VERSION: 5.5
      dockerfile: ./ci/unit/Dockerfile
  php56:
    build:
      context: .
      args:
        PHP_VERSION: 5.6
      dockerfile: ./ci/unit/Dockerfile
  php70:
    build:
      context: .
      args:
        PHP_VERSION: 7.0
      dockerfile: ./ci/unit/Dockerfile
  php71:
    build:
      context: .
      args:
        PHP_VERSION: 7.1
      dockerfile: ./ci/unit/Dockerfile
  laravel51:
    build:
      context: .
      args:
        LARAVEL_VERSION: 5.1
      dockerfile: ./ci/integration/Dockerfile
  laravel52:
    build:
      context: .
      args:
        LARAVEL_VERSION: 5.2
      dockerfile: ./ci/integration/Dockerfile
  laravel53:
    build:
      context: .
      args:
        LARAVEL_VERSION: 5.3
      dockerfile: ./ci/integration/Dockerfile
  laravel54:
    build:
      context: .
      args:
        LARAVEL_VERSION: 5.4
      dockerfile: ./ci/integration/Dockerfile