steps:
  - label: ':php: 5.6 Unit'
    command:
      - .ci/unit.sh
    plugins:
      docker-compose#v2.5.0:
        run: php56
        env:
          - PUID=999
          - PGID=999
  - label: ':php: 7.0 Unit'
    command:
      - .ci/unit.sh
    plugins:
      docker-compose#v2.5.0:
        run: php70
        env:
          - PUID=999
          - PGID=999
  - label: ':php: 7.1 Unit'
    command:
      - .ci/unit.sh
    plugins:
      docker-compose#v2.5.0:
        run: php71
        env:
          - PUID=999
          - PGID=999
  - label: ':php: 7.2 Unit'
    command:
      - .ci/unit.sh
    plugins:
      docker-compose#v2.5.0:
        run: php72
        env:
          - PUID=999
          - PGID=999
  - wait
  - label: ':construction: Laravel 5.1 Smoke Test'
    command:
      - .ci/integration.sh
    plugins:
      docker-compose#v2.5.0:
        run: php72
        env:
          - PUID=999
          - PGID=999
  - label: ':construction: Laravel 5.2 Smoke Test'
    command:
      - .ci/integration.sh
    plugins:
      docker-compose#v2.5.0:
        run: php72
        env:
          - PUID=999
          - PGID=999
  - label: ':construction: Laravel 5.3 Smoke Test'
    command:
      - .ci/integration.sh
    plugins:
      docker-compose#v2.5.0:
        run: php72
        env:
          - PUID=999
          - PGID=999
  - label: ':construction: Laravel 5.4 Smoke Test'
    command:
      - .ci/integration.sh
    plugins:
      docker-compose#v2.5.0:
        run: php72
        env:
          - PUID=999
          - PGID=999
  - label: ':construction: Laravel 5.5 Smoke Test'
    command:
      - .ci/integration.sh
    plugins:
      docker-compose#v2.5.0:
        run: php72
        env:
          - PUID=999
          - PGID=999
