FROM php:7.1-alpine

WORKDIR /usr/src/app

COPY . .

VOLUME /usr/src/docs

RUN cp -r ./ci ../ci && \
    chmod +x ../ci/scripts/*.sh && \
    ../ci/scripts/setup.sh && \
    apk add --no-cache curl git && \
    chown -R www-data:www-data ..

USER www-data

RUN set PATH=/home/www-data/.composer/vendor/bin:$PATH && \
    curl -O http://get.sensiolabs.org/sami.phar && \
    composer global require justinwalsh/daux.io

CMD [ "bash", "../ci/scripts/docs.sh" ]