FROM php:5.6-alpine

WORKDIR /usr/src/app

ENV PHPUNIT_VERSION '5.7.19'

COPY . .

RUN chmod +x ./ci/scripts/*.sh
RUN ./ci/scripts/setup.sh

USER www-data

RUN ./ci/scripts/install.sh

CMD [ "sh", "./ci/scripts/test.sh" ]
