#!/bin/bash
export INTEGRATION_DIR="$HOME/integration"
cacheKey="laravel-semaphore-$LARAVEL_VERSION"
if cache has_key $cacheKey; then
    composer restore $cacheKey
else
    composer create-project laravel/laravel integration "${LARAVEL_VERSION}.*" --no-progress --no-dev $INTEGRATION_DIR
    cache store $cacheKey $INTEGRATION_DIR
fi