#!/bin/bash
set -euxo pipefail

# install laravel
export INTEGRATION_DIR="$HOME/integration"
cacheKey="laravel-semaphore-$LARAVEL_VERSION"
if cache has_key $cacheKey; then
    cache restore $cacheKey
else
    composer create-project laravel/laravel $INTEGRATION_DIR "${LARAVEL_VERSION}.*" --no-progress --no-dev
    cache store $cacheKey $INTEGRATION_DIR
fi

sudo apt install -y jq

# prepare laravel
export PLUGIN_DIR="$SEMAPHORE_GIT_DIR"
contents="$(jq \".repositories = [{\\\"packagist.org\\\": false}, {\\\"type\\\": \\\"path\\\", \\\"url\\\": \\\"$PLUGIN_DIR\\\"}, {\\\"type\\\": \\\"composer\\\", \\\"url\\\": \\\"https://packagist.org\\\"}]\" < $PLUGIN_DIR/composer.json)"
echo $contents
# echo "$contents" > composer.json
# composer require robbrazier/piwik:* --no-suggest --no-progress --update-no-dev
# sed -e 's/App\\Providers\\RouteServiceProvider::class,/App\\Providers\\RouteServiceProvider::class, RobBrazier\\Piwik\\PiwikServiceProvider::class/g' -i.bak config/app.php
# sed -e 's/Illuminate\\Support\\Facades\\View::class,/Illuminate\\Support\\Facades\\View::class, "Piwik" => RobBrazier\\Piwik\\Facades\\Piwik::class/g' -i.bak config/app.php
# filename="routes/web.php"
# if [ "${LARAVEL_VERSION}" = "5.1" ] || [ "${LARAVEL_VERSION}" = "5.2" ]; then
#     filename="app/Http/routes.php"
# fi
# cat "$APP_DIR/plugin/ci/scripts/routes.txt" > "$filename"
# cat "$APP_DIR/plugin/ci/scripts/config.txt" > "config/piwik.php"