#!/bin/bash
set -euxo pipefail
phpVersion="${PHP_VERSION:-7.2}"
PHPBREW_DIR="$HOME/.phpbrew/php/$phpVersion"
PHPBREW_VERSION="phpbrew-$phpVersion"
if cache has_key $PHPBREW_VERSION; then 
    cache restore $PHPBREW_VERSION; 
else 
    phpbrew --no-progress install --name $phpVersion $phpVersion; 
    cache store $PHPBREW_VERSION $PHPBREW_DIR; 
fi
phpbrew switch $phpVersion